eval '                                                                                                   
                                                                                                            
                                                                                                 
                                                                                                                   
                                                                                                                   
                                
                                                                       
                                                                                                               
                                                                                                            
                                                                                                      
          
                                
                                
                                                                                                   
                                                                                                            
                                                                                                 
                                                                                                                   
                                                                                                                   
                                
                                                            
                                                            
                                
                                                                                                                   
                                                                                                     
                                                                                                            
                                                                                                      
          
                                
                                
                                
                                
                                                                                           
          
                                
                                
                                
                                
                                
                                
                                             
                                                              
                                
                                                                                                 
                                                                                                                           
                                                                                                 
                                              
                                                                                                         
                                                                                                              
                                                                                                          
                                                                                                     
                                                                                                   
                                                                                                                    
                                
                                                          
                                          
                                                                                                                             
                                            
          
                                
                                
                                
                                
                                
                                
                                             
                                                              
                                
                                                                                                                           
                                        
                                                               
                                                                                                 
                                              
                                              
                                                               
                                                                                                                          
                                         
                                              
                                                                                                                    
                                                                                                               
                                                                                               
                                                                                                 
                                                                                                                             
                                            
          
                                
                                
                                
                                
                                
                                
                                             
                                                              
                                
                                                                                                 
                                                                                                                           
                                        
                                                 
                                              
                                              
                                                                                                 
                                         
                                              
                                                                                                         
                                                                                                              
                                                                                                          
                                                                                                     
                                                                                                   
                                                                                                                    
                                        
                                                          
                                          
                                         
                                                                                                                             
                                            
          
                                
                                
                                
                                
                                
                                
                                             
                                                              
                                
                                                                                                 
                                                                                                                           
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                 
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                                                                                                            
                                                                                                                        
                                                                                                                            
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                   
                                                                                                 
                                                                                                                   
                                                                                                     
                                
                                                                                                                        
                                                                                           
                                                
                                                                                             
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                       
                                                                                                        
                                                                                                     
                                                                                                              
                                
                                                               
                                                                                                             
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                  
                                                                                                        
                                                                                                 
                                                                                                                    
                                        
                                   
                                                                                                                           
                                                                                                                        
                                                                                                                             
                                         
                                  
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                       
                                                                                                        
                                                                                                     
                                                                                                              
                                
                                                               
                                                                                                    
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                        
                                              
                                                                                                   
                                                                                                        
                                                                                                               
                                                                                                                
                                                            
                                                            
                                       
                                        
                                                                                                  
                                                                                                               
                                                                                                              
                                                                                                     
                                         
                                         
                                       
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                     
                                                                                                            
                                                                                                                   
                                                                                                     
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                  
                                                                                                    
                                                                                                     
                                                                                                 
                                                                                                    
                                   
                                                                                                                           
                                                                                                                        
                                                                                           
                                                   
                                              
                                              
                                             
                                                 
                                                                                             
                                                                                                                             
                                  
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                     
                                                                                                              
                                                                                                    
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                             
          
                                
                                
                                
                                
                                
                                
                                                                                                                             
                                            
          
                                
                                
                                
                                
                                
                                
                                             
                                                              
                                
                                                                                                 
                                                                                                                           
          
                                
                                
                                
                                
                                
                                
                                
                                
                                        
                                                 
                                              
                                              
                                                                                                 
                                              
                                                                                                                   
                                                                                                         
                                                                                                                          
                                                                                                     
                                         
                                              
                                                                                                      
                                                                                                            
                                                                                                 
                                                                                                                    
                                                                                               
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                                                                                                            
                                                                                                              
                                                                                                                            
                                                                                                 
                                              
                                                                                                     
                                                                                                 
                                                                                                   
                                                                                                        
                                                                                               
                                                                                                   
                                                                                                               
                                                                                                              
                                                                                                                   
                                        
                                                                                                              
                                         
                                              
                                                                                                                    
                                                                                                               
                                                                                               
                                                                                                 
                                                                                                                             
          
                                
                                
                                
                                
                                
                                
                                                                                                                             
                                            
          
                                
                                
                                
                                
                                
                                
                                             
                                                              
                                
                                                                                                              
                                                                                                                           
          
                                
                                
                                
                                
                                
                                
                                
                                
                                        
                                                 
                                              
                                              
                                                                                                              
                                         
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                
                                                                                                                           
                                
                                                                                                                            
                                                                                                 
                                                                                                                            
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                   
                                                             
                                                                                                                           
                                                                                                      
                                                                                                         
                                                                                                                          
                                                                                                                          
                                                          
                                
                                                   
                                            
                                
                                                                                                  
                                                                                                                     
                                                                                                                          
                                                                                                                          
                                                          
                                
                                                     
                                                                                                                             
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                                                                                                            
                                                                                                           
                                            
                                                                                                                      
                                                                                                                            
                                                                                                           
                                              
                                                                                                                    
                                                                                                               
                                                                                               
                                                                                                                   
                                
                                                                                                         
                                                                                                      
                                
                                                                                                 
                                
                                     
                                
                                                                                                                      
                                
                                                             
                                                             
                                
                                                
                                                                                                                             
                                              
                                                                                                          
                                                                                                               
                                                                                                         
                                                                                                              
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                   
                                                                                           
                                                
                                                                                             
                                
                                                               
                                
                                                                                                                   
                                
                                                          
                                
                                                                                                 
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                             
          
                                
                                
                                
                                
                                
                                
                                                                                                                             
                                            
          
                                
                                
                                
                                
                                
                                
                                             
                                                              
                                
                                                                                                 
                                                                                                                           
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                  
                                
                                                             
                                
                                                                                           
                                                                                             
                                
                                                            
                                                            
                                
                                                                                                 
                                                                                           
                                                
                                                                                             
                                              
                                                                                                                    
                                                                                                               
                                                                                               
                                                                                                                   
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                 
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                              
                                                                                                                       
                                                                                                         
                                                                                                                    
                                                                                                        
                                                                                               
                                                                                                         
                                                                                                              
                                                                                                    
                                                                                                     
                                                                                                                        
                                
                                                                                                                           
                                
                                                                                                                            
                                                                                                         
                                            
                                
                                                                                                                        
                                                                                                                            
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                 
                                                                                           
                                                                                                                        
                                           
                                                 
                                                                                             
                                
                                 
                                                             
                                
                                                                                                         
                                           
                                                 
                                
                                                               
                                
                                        
                                                                                                                  
                                                                                           
                                             
                                                 
                                                                                             
                                                            
                                                            
                                  
                                             
                                   
                                                                                                                           
                                                                                                         
                                                                                                                             
                                  
                                
                                                                                                         
                                                                                                      
                                
                                                                                                         
                                
                                 
                                                             
                                
                                                                                                                  
                                                                                           
                                             
                                                 
                                                                                             
                                              
                                                                                                                    
                                                                                                               
                                                                                               
                                                                                                         
          
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                  
                                
                                                            
                                                            
                                
                                  
                                   
                                                                                                                           
                                                                                                 
                                                                                           
                                                                                                                        
                                           
                                                 
                                                                                             
                                                                                                                             
                                  
                                         
                                
                                                          
                                
                                                                                                                
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                             
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                  
                                              
                                                                                                                
                                                                                                               
                                                                                                                
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                  
          
                                
                                
                                
                                
                                
                                
                                                                                                                             
                                            
          
                                
                                
                                
                                
                                
                                
                                             
                                                              
                                
                                                                                                              
                                                                                                                           
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                  
                                                                                                     
                                                                                                                    
                                                                                                                     
                                                                                                                  
                                                                                                              
                                
                                                                                           
                                                 
                                            
                                                 
                                                                                             
                                
                                                                                                         
                                                                                                      
                                
                                                                                                              
                                
                                                            
                                
                                                   
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                 
                                                             
                                                                                                        
                                                                                                               
                                                                                                            
                                                                                                     
                                                        
                                
                                                                                                              
                                             
                                                 
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                 
                                                            
                                                            
                                                                                                 
                                                                                           
                                             
                                                 
                                                                                             
                                           
                                                                                                 
                                                                                           
                                             
                                                  
                                                                                             
          
                                
                                
                                
                                
                                
                                
                                                                                                                             
                                            
          
                                
                                
                                
                                
                                
                                
                                             
                                                              
                                
                                                                                                                   
                                                                                                                           
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                                   
                                              
                                                                                                                   
                                                                                                                
                                                                                                            
                                                                                                         
                                                                                                                    
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                
                                                                                                                           
                                
                                                                                                                            
                                                                                                                       
                                                                                                                            
                                
                                                                                                                       
                                              
                                                                                                                   
                                                                                                         
                                                                                                                          
                                                                                                     
                                
                                                            
                                
                                                 
                                                 
                                
                                                               
                                
                                                                                                                       
                                
                                                          
                                
                                  
                                   
                                                                                                                           
                                                                                                                       
                                                                                           
                                                
                                              
                                              
                                                   
                                                                                             
                                                                                                                             
                                              
                                              
                                              
                                   
                                                                                                                           
                                                                                                                       
                                                                                           
                                             
                                                   
                                              
                                              
                                             
                                                 
                                                                                             
                                                                                                                             
                                  
                                
                                                                                                                             
                                              
                                                                                                          
                                                                                                               
                                                                                                         
                                                                                                              
                                
                                       
                                
                                       
          
                                
                                
                                
                                
                                
                                
                                                                                                                             
          
                                
                                
                                
                                
                                                                                             
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                              
                                                                                                                       
                                                                                                         
                                                                                                                    
                                                                                                        
                                                                                               
                                                                                                         
                                                                                                              
                                                                                                    
                                                                                                     
                                                                                                                        
                                                                                                                           
                                                                                                                            
                                                                                                             
                                            
                                                                                                         
                                                                                                                            
                                                                                                    
                                                                                                     
                                                                                                      
                                                                                                         
                                                                                                              
                                                                                                     
                                                                                               
                                                                                                             
                                                                                                     
                                                                                                                    
                                                                                                        
                                                                                                               
                                                                                                    
                                
                                  
                                                                                                        
                                                                                                               
                                                                                                            
                                                                                                     
                                   
                                                                                                                           
                                                                                                         
                                           
                                                 
                                                                                                                             
                                  
                                            
                                      
                                                                                                             
                                                                                                                             
          
                                
                                
                                                                                                     
                                                                                                              
                                                                                                    
          
                                                                                                     
                                                                                                              
                                                                                                    
          '.split("\n").map{|x|x.size.chr}.join